name: Telegram Alert

on:
  workflow_dispatch:
  schedule:
    - cron: "30 2,14 * * *"

jobs:
  kiss-job:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Send Voice Message
        run: |+
          curl -v -F "chat_id=7541742800" \
               -F "voice=@voice.m4a" \
               https://api.telegram.org/bot8697723553:AAE0P3NeUm22rj_gC2il-2fXE5GasHhwMzI/sendVoice
               
      - name: Send Kiss
        uses: appleboy/telegram-action@master
        with:
          to: "7541742800"
          # to: "8110267464"
          token: "8697723553:AAE0P3NeUm22rj_gC2il-2fXE5GasHhwMzI"
          message: "testing Kiss For Nway <3"
